spring:
  application:
    name: auth
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_core
    username: postgres
    password: postgres
  sql:
    init:
      mode: never
  security:
    oauth2:
      authorizationserver:
        client:
          demo:
            require-proof-key: false
            registration:
              client-id: demo-client
              client-secret: "{noop}demo-secret"
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
                - refresh_token
                - client_credentials
              redirect-uris:
                - http://127.0.0.1:8080/authorized
                - http://localhost:8080/authorized
              scopes:
                - openid
                - api.read

server:
  port: 8080
